### ISSUE TITLE
missing sprites in Castlevania III

### ISSUE THREAD

**Issue by sammachkovech** [agg23/openfpga-NES#1]
### Version (or build number)

0.1.0

### Steps to reproduce

load Castlevania III, any version. start game, enter name, watch intro sequence play. Simon will be invisible, but his whip will not.

### Expected Behavior

Simon should have appeared.

### Actual Behavior

Simon did not appear.

### Additional Context

Other enemies and sprites appear.

**Comment by agg23** [comment]
Interesting. I do not observe this, and CV3 was one of my main testing games. What version of the game are you using (US, Japan)? Is it using iNES 1 or 2.0?

**Comment by sammachkovech** [comment]
forgot to add some useful context: both USA versions I tested came from a certain no-intro collection (20220416-055527) reproduce this issue. I've since accessed another dump of the game that does *not* reproduce this issue. so the issue could possibly be thanks to a faulty dump, but you can find and test the ROM in question with the information listed here to confirm for yourself.

**Comment by agg23** [comment]
I found the ROM and verified the issue. I wonder if it works on MiSTer...

**Comment by retrocaster** [comment]
I just confirmed that the same issue occurs on my MiSTer when I use that same rom

**Comment by agg23** [comment]
Closing as upstream issue. Thanks for the report

**Comment by naveedster** [comment]
Maybe you should log it for the Mister core at https://github.com/MiSTer-devel/NES_MiSTer/issues

**Comment by retrocaster** [comment]
> Maybe you should log it for the Mister core at https://github.com/MiSTer-devel/NES_MiSTer/issues

Castlevania III works fine on MiSTer with known good roms. I think in this case there's something wrong with the rom.
