### ISSUE TITLE
Framework error

### ISSUE THREAD

**Issue by Elcron42** [agg23/openfpga-NES#10]
### Ask a question

I assume it is something I am doing wrong but I am getting an error when loading roms in the nes core. It reads "Error in framework can't find bitstream" for every rom I have tried.

**Comment by agg23** [comment]
You downloaded the wrong thing. You want to go to Releases on the right side and download the 'agg23.NES....zip' file on the latest release

**Comment by Elcron42** [comment]
Thank a ton, all good now.
