### ISSUE TITLE
SMB 3 Battery Hack Not Running

### ISSUE THREAD

**Issue by redonepunch** [agg23/openfpga-NES#13]
### Version (or build number)

0.1.0

### Steps to reproduce

- Super Mario Bros. 3 (USA).nes from Nintendo Entertainment System NES Roms (Europe/USA)
- SMB3_Battery Hack_v7 from romhacking.net
- Patch with Lunar IPS v1.03

### Expected Behavior

Patched rom runs on MiSTer NES core

### Actual Behavior

Patched rom does not run on Pocket NES core. I get a black screen

### Additional Context

n/a

**Comment by agg23** [comment]
Closing in favor of #5
