### ISSUE TITLE
missing Load Cartridge in Core Settings

### ISSUE THREAD

**Issue by brandonnn** [agg23/openfpga-NES#2]
### Ask a question

Great work on the core! It seems to be the first I've seen that doesn't have Load Cartridge in the Core Settings menu, though, meaning you have to quit and restart entirely to change games, unless I'm missing something super obvious.

Is this something end users can add in the Core files? (I dug around the files for your SNES core looking for where that might be hidden and couldn't find anything obvious!)

**Comment by agg23** [comment]
Not a bug (with the core, at least). SNES doesn't have it enabled anymore either (starting with 0.2.0) because you will lose save games by using the ROM change in the menu due to an Analogue firmware bug.

For the same reason, it is not safe for the NES core to have the option at the moment.

**Comment by brandonnn** [comment]
Understood -- thanks for the fast answer!
