### ISSUE TITLE
Missing graphics while using custom pallette 

### ISSUE THREAD

**Issue by IndoJimbo** [agg23/openfpga-NES#24]
Castlevania has missing hud while custom pallette is selected. 

![20221210_085344.jpg](https://user-images.githubusercontent.com/61066088/206859653-279c358d-6c2d-46ab-939e-7a6d2641f8fa.jpg)

**Comment by agg23** [comment]
I cannot replicate this. Did you change the custom palette mid-game (via `Load Custom Palette`)? I'm able to see the HUD just fine when switching between palettes.

**Comment by IndoJimbo** [comment]
Its working now, thats weird. Go ahead and close this issue I guess
