### ISSUE TITLE
Incorrect Audio in some games (noticed in Mega Man IV)

### ISSUE THREAD

**Issue by WobbleTheHutt** [agg23/openfpga-NES#28]
### Version (or build number)

0.3.1

### Steps to reproduce

we discussed this on discord, at the very least the audio is off in mega man IV and was confirmed by you. easily check by jumping and todman's stage music is way off.

### Expected Behavior

audio should sound identical to the NES/ Spirtualized core.

### Actual Behavior

Audio at least in mega man IV is just plain wrong vs the original.

**Comment by agg23** [comment]
Issue is likely due to lack of MiSTer's audio filtering pipeline. A build adding these components is currently in testing.

**Comment by WobbleTheHutt** [comment]
> Issue is likely due to lack of MiSTer's audio filtering pipeline. A build adding these components is currently in testing.

Tested the version you posted on discord. Sounds resolved!

**Comment by agg23** [comment]
Released in 1.0.0
