### ISSUE TITLE
Can't seem to save state in several games

### ISSUE THREAD

**Issue by neutralinsomniac** [agg23/openfpga-NES#3]
### Version (or build number)

0.1.1

### Steps to reproduce

Tried hitting analogue+up to save state in Ninja Gaiden, Dragon Warrior, and Final Fantasy, and all three give a Save Failed error. These are the only games I've tried so far.

### Actual Behavior

See Steps to reproduce. Pretty straightforward :)

**Comment by agg23** [comment]
Save states are not supported, only game saves

**Comment by neutralinsomniac** [comment]
Ahhh my bad. I conflated "saves" with "save states" in the readme.
