### ISSUE TITLE
Core resets after loading custom palettes

### ISSUE THREAD

**Issue by icelaglace** [agg23/openfpga-NES#31]
### Version (or build number)

0.3.1

### Steps to reproduce

- Load the core
- Load game

- Select “Custom” in Palettes
- Select “Load Custom Palette”
- Select your palette

- Go back to the game
- Re-select the same palette
- Repeat going back to the game and selecting the palette until the core resets the game as it’s random but does happen fast. 

### Expected Behavior

Core shouldn’t reset

### Actual Behavior

Core resets upon loading the palette in some occasions.

**Comment by agg23** [comment]
Released in 1.0.0
