### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by mddifilippo89** [agg23/openfpga-NES#34]
### Version (or build number)

1.0.0

### Steps to reproduce

Run Mega Man VI, navigate to level-select screen.
Mario Bros seems okay. I also notice this with Mighty Final Fight.

### Expected Behavior

Video is centered

### Actual Behavior

There is a noticeable black bar running down the left of the screen. (pocket)

**Comment by agg23** [comment]
That's how NES overscan works. The core has an `Edge Masking` setting, which by default is automatic. You could set it to `Mask Right` to "center" the video, but it will break on other titles. `Auto Masking` is generally the correct setting.

**Comment by mddifilippo89** [comment]
That's fine, but it appears some capcom games like mega man IV just don't respond to any changes made to the Edge Masking (which there is no MaskRight option by the way).
