### ISSUE TITLE
Unable to see NES as system in menu

### ISSUE THREAD

**Issue by nlen83** [agg23/openfpga-NES#6]
### Version (or build number)

0.1.1

### Steps to reproduce

Copied over zip contents and then added rom to assets/common

### Expected Behavior

I expected to see NES listed as a system in the analogue for settings

### Actual Behavior

I can load a game but have no core settings. The NES is not listed as a system in my analogue pause menu or menus in general. The only thing I can do is launch NES rom

**Comment by agg23** [comment]
How are you able to launch a ROM if you can't see the NES?

Sounds like you didn't copy the core files over correctly. Your `Cores/agg23.NES` folder should have all of the files that the corresponding folder in the zip has: `audio.json`, `core.json`, `interact.json`, etc...

Not an issue with the core. Closing

**Comment by nlen83** [comment]
Thanks for the reply Adam. I mean, the core settings is unavailable. I simply copied over all the contents of the zip for 0.1.1. It’s probably something I did. Take careSent from my iPhoneOn Sep 27, 2022, at 7:07 PM, Adam Gastineau ***@***.***> wrote:﻿
How are you able to launch a ROM if you can't see the NES?
Sounds like you didn't copy the core files over correctly. Your Cores/agg23.NES folder should have all of the files that the corresponding folder in the zip has: audio.json, core.json, interact.json, etc...
Not an issue with the core. Closing
